version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:5000
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    env_file:
      - src/backend/.env
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

  # Local databases - only start these if you want local development
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
    profiles:
      - local

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j-data:/data
    networks:
      - app-network
    profiles:
      - local

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    profiles:
      - local

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
  neo4j-data:
  redis-data:
